# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: app01
build:
  artifacts:
#  - image: skaff old-buildpa cks # old name
  - image: skaf-app01-python-buildpacks
    #context: my-python-app # not sure what this is for.. this should point to the folder in which the Procfile resides, will default to . I believe
    # sync:
      # buildpacks filesync support for python is not available: https://skaffold.dev/docs/pipeline-stages/filesync/
      # use either manual sync or skip this
      # infer is not supported for buildpacks
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true
      dependencies:
        paths:
          - '*.py'
          - requirements.txt
          - project.toml
          - Procfile
          - VERSION
        ignore:
          - k8s/**
deploy:
  # Adding just for Python to see if stabilization gets better with CD b/239385876
  #  https://skaffold-latest.firebaseapp.com/docs/pipeline-stages/status-check/
  statusCheckDeadlineSeconds: 300
  kustomize: # uses kustomize
    paths: [./k8s/base]
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  - name: dev
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/dev]
  - name: staging
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/staging]
  - name: canary
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/canary]
  - name: production
    deploy:
      kustomize: # uses kustomize
        paths: [./k8s/overlays/production]
  - name: canary-sol2
    deploy:
      kustomize:
        paths: [./k8s/overlays/canary-sol2]
  - name: production-sol2
    deploy:
      kustomize:
        paths: [./k8s/overlays/production-sol2]

# TODO skaffold profile for solutions. then use with skaffold render or CD release CLI.
#   - name: canary-solution1
#   - name: canary-solution1
  # - name: canary-solution1
  #   deploy:
  #     kustomize: # uses kustomize
  #       paths: [./k8s/overlays/canary]
