

skaffold-dev:
	./skaffold-wrapper.sh dev

skaffold-run-dev:
	./skaffold-wrapper.sh run -p dev
skaffold-run-canary:
	./skaffold-wrapper.sh run -p canary



test:
	echo Lets pretend this doesnt build.
	/bin/false
