

skaffold-dev:
	./skaffold-wrapper.sh dev

skaffold-run-dev:
	./skaffold-wrapper.sh run -p dev
skaffold-run-canary:
	./skaffold-wrapper.sh run -p canary



test:
	echo Text fixed now all good
	ruby ruby-app/app.rb
	echo Looks like Ruby app returns so looks like no Syntax Horrors.
#	echo Lets pretend this doesnt build.
#	/bin/false
